spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: client-service-auth
          uri: https://client-service-qd9e.onrender.com
          predicates:
            - Path=/client-service/auth/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
