

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis
      - discovery-server
    env_file:
      - .env
    environment:
    - SPRING_APPLICATION_NAME=client-service
    - SPRING_PROFILES_ACTIVE=default
    - JWT_SECRET
    - MYSQL_URL
    - MYSQL_USERNAME
    - MYSQL_PASSWORD
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - SPRING_REDIS_HOST=redis
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    environment:
      - SPRING_APPLICATION_NAME=discovery-server
      - EUREKA_SERVER_PORT=8761

networks:
  app-network:
    driver: bridge
